language: go
go:
- tip
before_deploy:
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: MwYNLrxC1HjF9i5WQXHdfO1VDTZ9dWNXTuLIPWAeH5YnGL8jhUP6b21aEeZsAI/2GGEu6B3XOHESHFFEMgqhXycBzbaYl1REa7ka4r8dxUrITj0W7L6JhN9uuYIHsCPoSMNM3c2dODzmlTmehYvXfclBb7ioYr4n7hQEZNwVlqYCjuoteMEiBO6ShhPiNzts+UtDt5t7cjUmw7cTaazQ/w7yTlB0BqVY2FSE8AgLMqLRUAyqYy/ibhGwfNcdbFybRGouwXDYKX+ce4auvP+iA8g/8ckieMAQ19O9HSaGu7h8ymD5RJLTkvNkgbVd4ZKKTpWv/ilRwOsr61TwkeUQASKhOs7dYhkz8EfjbPs8pPl9+i5UmJBaoKUgUDIxtjplmNKqSPWwbJCypmxmaQY31GuhBE9DvkPLFiMIzp0XmuqkWAu3sSbG9oSOXYLqYTQaSxkJr5S/uee+1IdtCLUMNuG9sIIlD7CE6WVjM9628Dkmzz+BM6GJkF7tSOymzIHV31mgzO4I2/JuT1hq3mtpHahgN59N9k/sCp4nfp+8JvFsAwov7UUF0ZCopUQw82jnZjgL616cJ18izLoQHwn92PYmXPjr6ZEPpkhZwTF73ExTqRjIaDxoKUm9XL3osRz9899sblQXXhDjijA+s6KdPlua9QyIddP+xFt8kpBp2xM=
  file: bin/ddns
  skip_cleanup: true
  on:
    tags: true
